jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install project dependencies
      run: npm install

    - name: Build project without treating ESLint warnings as errors
      env:
        CI: false  # Set CI environment variable to false
      run: npm run build  # Run the build command without treating ESLint warnings as errors
